df <- data.frame(
    Title = sprintf("Allen Brain Map Human M1 RNA-seq %s", c("logcounts", "colData")),
    Description = sprintf("%s 127 aggregated cell type expression profiles derived from the trimmed means of 76533 single cell nuclei from the primary motor cortex of 2 human brain specimens generated by the Allen Brain Map", 
        c("Matrix of log-normalized values from", "Per-cell type metadata containing labels of")),
    RDataPath = file.path("celldex", "allen_m1","1.0.0", c("logcounts.rds", "coldata.rds")),
    BiocVersion="3.12", 
    Genome=NA, 
    SourceType="CSV", 
    SourceUrl="https://portal.brain-map.org/atlases-and-data/rnaseq/human-m1-10x",
    SourceVersion="AllenBrainMap 1",
    Species="Homo sapiens", 
    TaxonomyId="9606",
    Coordinate_1_based=NA, 
    DataProvider="Allen Brain Map",
    Maintainer="Jared Andrews <jared.andrews07@gmail.com>",
    RDataClass=c("matrix", "DataFrame"), 
    DispatchClass="Rds", 
    stringsAsFactors = FALSE
)

write.csv(file="../../extdata/1.0.0/metadata-allen_m1.csv", df, row.names=FALSE)
